# Site settings
title: Game Dev @ UC
description: Student Group, University of Cincinnati, Game Development, Video Games, Analog Games, Games, Board Games, Unity, Unity3D
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Game Development Group
user_description: Student group about Game Development.
user_title: @ The University of Cincinnait
email: ucgamedevgroup@gmail.com
twitter_username: gamedevcincy
github_username:  gamedevcincy
gplus_username:  ucgamedevcincy

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
