# Site settings
title: "GameDevCincy"
description: Student Group, University of Cincinnati, Game Development, Video Games, Analog Games, Games, Board Games, Unity, Unity3D
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Game Dev Cincy
user_description: Welcome to the Game Devlopment Group at UC. We are a growing community of students interested in creating interacive multimedia (aka. Games!). Wether you come from a business, medical, humanities, art, or engineering background, all are welcome! Our goal is to create a thriving community of students at UC that are passionate about creating games and give them the resources to succeed.
user_title: ""
email: "ucgamedevgroup@gmail.com"
twitter_username: DevCincy
github_username:  gamedevcincy
gplus_username:  ucgamedevcincy

# Google-analytics
google-analytics:
  id: UA-125391325-1

exclude: ['package.json', 'src' , 'node_modules']
