# Site settings
title: "Game Dev @ UC"
description: Student Group, University of Cincinnati, Game Development, Video Games, Analog Games, Games, Board Games, Unity, Unity3D
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Game Dev Group
user_description: Welcome to the Game Devlopment Group at UC. We are a growing community of students interested in creating interacive multimedia (aka. Games!). We are open to students of all backgrounds wether you come from a buiness background, medical, musical, art, or engineering. Our goal is to create a thriving community of students at UC that are passionate about creating games and give them the resources to succeed.
user_title: "Student Group at UC"
email: "ucgamedevgroup@gmail.com"
twitter_username: DevCincy
github_username:  gamedevcincy
gplus_username:  ucgamedevcincy

# Google-analytics
google-analytics:
  id: "UA-125391325-1"

exclude: ['package.json', 'src' , 'node_modules']
